default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: loyalty_program_dev

test:
  <<: *default
  database: loyalty_program_test
